- id: sunset
  alias: Sunset Report
  trigger:
    platform: sun
    event: sunset
    offset: -01:30
  action:
    - service: notify.telegram_notify
      data_template:
        title: Temperature Summary
        message: "Summary for Sunset: \nBedroom, {{ states.sensor.temperature_bedroom.state }} C / {{ states.sensor.humidity_bedroom.state }} %\nLivingroom, {{ states.sensor.temperature_livingroom.state }} C / {{ states.sensor.humidity_livingroom.state }} %\nFunroom, {{ states.sensor.temperature_funroom.state }} C / {{ states.sensor.humidity_funroom.state }} %\nTerrarium, {{ states.sensor.temperature_terrarium.state }} C / {{ states.sensor.humidity_terrarium.state }} %"

- id: temp
  alias: Temperature Alert
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_bedroom
    above: 23
  action:
    - service: notify.telegram_notify
      data_template:
        message: "Temperature above 23 in Bedroom: \nBedroom, {{ states.sensor.temperature_bedroom.state }} C / {{ states.sensor.humidity_bedroom.state }} %\nLivingroom, {{ states.sensor.temperature_livingroom.state }} C / {{ states.sensor.humidity_livingroom.state }} %\nGuestroom, {{ states.sensor.temperature_guestroom.state }} C / {{ states.sensor.humidity_guestroom.state }} %"

- id: tempLowFun
  alias: Temp too low in Funroom
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_funroom
    below: 20
  action:
    - service: notify.telegram_notify
      data_template:
        message: "Temperature too low in FunRoom! \nCurrently: {{ states.sensor.temperature_funroom.state }} C / {{ states.sensor.humidity_funroom.state }} %"

- id: tempHighFun
  alias: Temp too high in Funroom
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_funroom
    above: 32
  action:
    - service: notify.telegram_notify
      data_template:
        message: "Temperature too high in FunRoom! \nCurrently: {{ states.sensor.temperature_funroom.state }} C / {{ states.sensor.humidity_funroom.state }} %"

- id: humLowTerr
  alias: Low Humidity in Terrarium
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_terrarium
    below: !secret terr_humidity_limit
  action:
    - service: notify.telegram_notify
      data_template:
        message: "Humidity too low in Terrarium!\nCurrently: {{ states.sensor.humidity_terrarium.state }} %"

- id: tempHighTerr
  alias: High Temp in Terrarium
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_terrarium
    above: !secret terr_temp_upper_limit
  action:
    - service: notify.telegram_notify
      data_template:
        message: "Temperature too high in Terrarium!\nCurrently: {{ states.sensor.temperature_terrarium.state }} %"

- id: humidity_bedroom
  alias: Humidity Bedroom Alert
  trigger:
    platform: numeric_state
    entity_id: sensor.humidity_bedroom
    above: 65
  action:
    - service: notify.telegram_notify
      data_template:
        message: "Too much humidity in bedroom: \n{{ states.sensor.humidity_bedroom.state }} %"

- id: webcamimagesmorning
  alias: Daily Morning Webcam Images
  trigger:
     platform: time
     at: '07:00:00'
  action:
    - service: telegram_bot.send_photo
      data:
         file: /tmp/lastsnap.jpg

- id: webcamimagesevening
  alias: Daily Evening Webcam Images
  trigger:
     platform: time
     at: '19:00:00'
  action:
    - service: telegram_bot.send_photo
      data:
         file: /tmp/lastsnap.jpg


- id: telegram
  alias: 'Telegram bot that reply pong to ping'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    - service: notify.telegram_notify
      data:
        message: 'pong'

- id: telegramLightOff
  alias: 'Switch off all Lights via Telegram'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/lightsoff'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: shell_command.kitchen_off

- id: telegramAlarmOn
  alias: 'Alarms on via Telegram'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/alarmon'
  action:
    - service: automation.turn_on
      entity_id: automation.main_door_alarm
    - service: automation.turn_on
      entity_id: automation.fun_door_alarm
    - service: notify.telegram_notify
      data:
        message: 'Alarms enabled'

- id: telegramAlarmOff
  alias: 'Alarms off via Telegram'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/alarmoff'
  action:
    - service: automation.turn_off
      entity_id: automation.main_door_alarm
    - service: automation.turn_off
      entity_id: automation.fun_door_alarm
    - service: notify.telegram_notify
      data:
        message: 'Alarms disabled'

- id: telegramWebcamRequest
  alias: 'Request Webcam image via Telegram'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/webcam'
  action:
    - service: telegram_bot.send_photo
      data:
         file: /tmp/lastsnap.jpg

- id: telegramTemperatureRequest
  alias: 'Request Temperature Summary via Telegram'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/temperature'
  action:
    - service: notify.telegram_notify
      data_template:
        title: Temperature On Demand
        message: "Summary on Demand: \nBedroom, {{ states.sensor.temperature_bedroom.state }} C / {{ states.sensor.humidity_bedroom.state }} %\nLivingroom, {{ states.sensor.temperature_livingroom.state }} C / {{ states.sensor.humidity_livingroom.state }} %\nFunroom, {{ states.sensor.temperature_funroom.state }} C / {{ states.sensor.humidity_funroom.state }} %\nTerrarium, {{ states.sensor.temperature_terrarium.state }} C / {{ states.sensor.humidity_terrarium.state }} %"

- id: bedroomMotion
  alias: 'Motion in bedroom'
  trigger:
    platform: state
    entity_id: sensor.motion_bedroom
    to: 'on'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: light.turn_on
      data:
        entity_id: group.bedroom
        brightness: 50

- id: bedroomMotionOff
  alias: 'Turn off bedroom light delayed'
  trigger:
    platform: state
    entity_id: sensor.motion_bedroom
    to: 'off'
    for:
      minutes: 2
  action:
    service: light.turn_off
    entity_id: group.bedroom

- id: mainDoorAlarm
  alias: 'Main Door Alarm'
  trigger:
    platform: state
    entity_id: sensor.door_alarm
    to: 'on'
  action:
    - service: notify.telegram_notify
      data:
        message: 'Main-Door was opened'

- id: funDoorAlarm
  alias: 'Fun Door Alarm'
  trigger:
    platform: state
    entity_id: sensor.fun_door_alarm
    to: 'on'
  action:
    - service: notify.telegram_notify
      data:
        message: 'Funroom-Door was opened'

- id: kitchenOn
  alias: 'Kitchen Light On'
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.kitchen_light
    to: 'on'
  action:
    service: shell_command.kitchen_on

- id: kitchenOff
  alias: 'Kitchen Light Off'
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.kitchen_light
    to: 'off'
  action:
    service: shell_command.kitchen_off

- id: xmasOn
  alias: 'XMas Light On'
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.xmas_light
    to: 'on'
  action:
    service: shell_command.xmas_on

- id: xmasAutoOn
  alias: 'XMas Light AutoOn'
  trigger:
    platform: sun
    event: sunset
    offset: 02:00
  action:
    service: shell_command.xmas_on

- id: xmasOff
  alias: 'XMas Light Off'
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.xmas_light
    to: 'off'
  action:
    service: shell_command.xmas_off

- id: xmasAutoOff
  alias: 'XMas Light AutoOff'
  trigger:
    platform: time
    at: '21:00:00'
  action:
    service: shell_command.xmas_off

#automation movie:
#  alias: Movie
#  triggerMainMainMainMainMainMain      :
#    platform: state
#    entity_id: media_player.amazon_fire_tv
#    to: 'playing'
#  condition:
#    condition: state
#    entity_id: sun.sun
#    state: 'below_horizon'
#  action:
#    service: scene.turn_on
#    entity_id: scene.movies


